language: python

python:
  - '2.7'

sudo: false

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - debian-sid 
    packages:
      - shellcheck

before_script:
  - pip install flake8 radon
  - npm install -g jshint
  - shellcheck --version

script: ./bin/check.sh
